const fs = require("fs-extra");
const path = require("path");
const chalk = require("chalk");
const { parseEnv, isSensitiveKey, normalizeTrailingNewline } = require("../utils/parseEnv");
const { trackUsage } = require("../core/telemetry");
const { resolveEnvPath, resolveEnvFilename } = require("../utils/fileHandler");
const logger = require("../utils/logger");

async function generateCommand(options, command) {
  await trackUsage("generate");

  const envFilename = resolveEnvFilename(command);
  const envPath = resolveEnvPath(command);
  const targetExamplePath = path.join(process.cwd(), ".env.example");

  console.log(chalk.cyan.bold("\n  📝 Generate .env.example\n"));

  const exists = await fs.pathExists(envPath);
  if (!exists) {
    console.error(chalk.red(`  ❌ No ${envFilename} found to generate example from.\n`));
    return;
  }

  const content = await fs.readFile(envPath, "utf-8");
  const parsed = parseEnv(content);
  const lines = [];

  for (const item of parsed) {
    if (isSensitiveKey(item.key)) {
      lines.push(`${item.key}=`);
      logger.verbose(`Stripped sensitive value for: ${item.key}`);
    } else {
      lines.push(`${item.key}=${item.value}`);
    }
  }

  if (lines.length === 0) {
    console.log(chalk.yellow(`  ⚠️  Nothing to generate. ${envFilename} is empty.\n`));
    return;
  }

  const header = `# ═══════════════════════════════════════════\n# .env.example — Generated by envman\n# Fill in the values below for your environment\n# ═══════════════════════════════════════════\n\n`;
  await fs.writeFile(targetExamplePath, header + normalizeTrailingNewline(lines.join("\n")), "utf-8");

  console.log(chalk.green(`  ✅ Generated .env.example with ${lines.length} variable(s).`));
  console.log(chalk.gray("     Sensitive values have been stripped.\n"));
}

module.exports = {
  generateCommand,
};
