const fs = require("fs-extra");
const path = require("path");
const chalk = require("chalk");
const readline = require("readline");
const crypto = require("crypto");
const { trackUsage } = require("../core/telemetry");
const { generateKey, saveProjectKey, hasKey } = require("../core/keyManager");
const logger = require("../utils/logger");

const DEFAULT_ENV_CONTENT = `# ═══════════════════════════════════════════
# Environment Variables — Generated by envman
# ═══════════════════════════════════════════

# Server
PORT=3000
NODE_ENV=development

# Database
DB_HOST=localhost
DB_PORT=5432
DB_NAME=myapp
DB_USER=postgres
DB_PASSWORD=your_password_here

# Authentication
JWT_SECRET=your_jwt_secret_here
SESSION_SECRET=your_session_secret_here

# API Keys
API_KEY=your_api_key_here
`;

function ask(question) {
  if (global.__mockReadline) {
    return Promise.resolve(global.__mockReadline.shift() || "");
  }
  return new Promise((resolve) => {
    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
    });
    rl.question(question, (answer) => {
      rl.close();
      resolve(answer.trim());
    });
  });
}

async function initCommand(options, command) {
  await trackUsage("init");
  const isSafe = command && command.optsWithGlobals ? command.optsWithGlobals().safe : false;

  console.log(chalk.cyan.bold("\n  🚀 Envman Project Setup\n"));

  const envPath = path.join(process.cwd(), ".env");
  const examplePath = path.join(process.cwd(), ".env.example");
  const gitignorePath = path.join(process.cwd(), ".gitignore");

  const envExists = await fs.pathExists(envPath);
  const exampleExists = await fs.pathExists(examplePath);
  const gitignoreExists = await fs.pathExists(gitignorePath);
  const keyExists = await hasKey();

  let actions = [];

  // ── Step 1: Create .env ──
  if (!envExists) {
    actions.push("create .env");
  } else {
    console.log(chalk.gray("  ✓ .env already exists."));
  }

  // ── Step 2: Create .env.example ──
  if (!exampleExists) {
    actions.push("create .env.example");
  } else {
    console.log(chalk.gray("  ✓ .env.example already exists."));
  }

  // ── Step 3: Ensure .gitignore has .env ──
  if (!gitignoreExists) {
    actions.push("create .gitignore");
  } else {
    const content = await fs.readFile(gitignorePath, "utf-8");
    if (!content.includes(".env")) {
      actions.push("update .gitignore");
    } else {
      console.log(chalk.gray("  ✓ .gitignore already ignores .env."));
    }
  }

  // ── Step 4: Generate encryption key ──
  if (!keyExists) {
    actions.push("generate AES-256 key");
  } else {
    console.log(chalk.gray("  ✓ Encryption key already configured."));
  }

  if (actions.length === 0) {
    console.log(chalk.green("\n  ✅ Project is already fully initialized.\n"));
    console.log(chalk.gray("  Run envman doctor to check environment health.\n"));
    return;
  }

  console.log(chalk.white("\n  Actions to perform:"));
  for (const action of actions) {
    console.log(chalk.yellow(`    → ${action}`));
  }

  if (isSafe) {
    console.log(chalk.yellow("\n  [SAFE MODE] No files were changed.\n"));
    return;
  }

  console.log("");

  // Execute actions
  if (actions.includes("create .env")) {
    await fs.writeFile(envPath, DEFAULT_ENV_CONTENT, "utf-8");
    console.log(chalk.green("  ✅ Created .env with template variables."));
  }

  if (actions.includes("create .env.example")) {
    // Strip sensitive values for example
    const exampleContent = DEFAULT_ENV_CONTENT
      .replace(/=your_.*_here/g, "=")
      .replace(/=postgres$/gm, "=");
    await fs.writeFile(examplePath, exampleContent, "utf-8");
    console.log(chalk.green("  ✅ Created .env.example."));
  }

  if (actions.includes("create .gitignore")) {
    await fs.writeFile(gitignorePath, ".env\n.env.*\n!.env.example\n.envmanrc\n.envman-backups/\nnode_modules/\n", "utf-8");
    console.log(chalk.green("  ✅ Created .gitignore with .env exclusions."));
  } else if (actions.includes("update .gitignore")) {
    await fs.appendFile(gitignorePath, "\n.env\n.envmanrc\n.envman-backups/\n", "utf-8");
    console.log(chalk.green("  ✅ Updated .gitignore to exclude .env."));
  }

  if (actions.includes("generate AES-256 key")) {
    const key = generateKey();
    await saveProjectKey(key);
    console.log(chalk.green("  ✅ Generated AES-256 encryption key → .envmanrc"));
    console.log(chalk.yellow("  ⚠️  Add .envmanrc to .gitignore to keep your key safe!"));
  }

  console.log(chalk.green.bold("\n  🎉 Project initialized successfully!\n"));
  console.log(chalk.gray("  Next steps:"));
  console.log(chalk.gray("    envman add DB_PASSWORD=mySecretPass"));
  console.log(chalk.gray("    envman doctor"));
  console.log(chalk.gray("    envman scan\n"));
}

module.exports = {
  initCommand,
};
